title: Anabel Ajaga
logo: /data.jpeg
description: I am a Data Analysts/BI Developer with hands-on experience on data analysis using advance excel for report automation,ETL pipelines and Power BI for Business insights .
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
